#!/bin/bash

ENV_FILES_PATH=/root/bin

if [[ $# -eq 0 ]]; then
    	echo "Usage: $0 <env_vars> <action>"
	exit 1
fi

echo "Sourcing ${ENV_FILES_PATH}/${1}"
# shellcheck source=/dev/null
source $ENV_FILES_PATH/$1

if [[ $2 =~ [Bb]ackup ]]; then
	if [[ $MAX_UPLOAD_RATE -eq 0 ]]; then
		restic backup --exclude-caches -x "$PATH_TO_BACKUP"
	else
		restic --limit-upload "$MAX_UPLOAD_RATE" backup --exclude-caches -x "$PATH_TO_BACKUP"
	fi
fi

if [[ $2 =~ [Cc]lean ]]; then
	restic forget \
	${RESTIC_KEEP_HOURLY:+--keep-hourly ${RESTIC_KEEP_HOURLY}} \
	${RESTIC_KEEP_DAILY:+--keep-daily ${RESTIC_KEEP_DAILY}} \
	${RESTIC_KEEP_WEEKLY:+--keep-weekly ${RESTIC_KEEP_WEEKLY}} \
	${RESTIC_KEEP_MONTHLY:+--keep-monthly ${RESTIC_KEEP_MONTHLY}} \
	${RESTIC_KEEP_YEARLY:+--keep-yearly ${RESTIC_KEEP_YEARLY}}
fi

if [[ $2 =~ [Cc]heck ]]; then
	restic check
fi

if [[ $2 =~ [Pp]rune ]]; then
	restic prune
fi

if [[ $2 =~ [Rr]ebuild-index ]]; then
	restic rebuild-index
fi

if [[ $2 =~ [Ss]napshots ]]; then
	restic snapshots
fi

if [[ $2 =~ [Ss]tats ]]; then
	restic stats
fi

if [[ $2 =~ [Uu]nlock ]]; then
	restic unlock
fi
